import { useParams, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { getOutputs } from "../utils/outputs";
import { getSetList } from "../utils/setlists";
import ChordSheetJS from "chordsheetjs";
import { Key } from "chordsheetjs";
import { Guitar } from "lucide-react";
import { supabase } from "../supabaseClient";

const SetListView = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [setlist, setSetlist] = useState(null);
    const [outputs, setOutputs] = useState([]);

    useEffect(() => {
        const fetchSet = async () => {
            const setlistData = await getSetList(id);
            const outputData = await getOutputs(id);
            
            setSetlist(setlistData);
            setOutputs(outputData);
            document.title = `Team Chords - ${setlistData.name}`;
        };
        fetchSet();
        
        const channels = supabase.channel('custom-filter-channel')
        .on(
            'postgres_changes',
            { event: '*', schema: 'public', table: 'setlists', filter: `id=eq.${id}` },
            (payload) => {
                fetchSet();
            }
        )
        .subscribe();
    }, [id]);

    useEffect(() => {
        if (outputs.length > 0) {
            document.querySelectorAll('.sheet h1').forEach((element) => {
                element.style.fontWeight = 'bold';
                element.style.textAlign = 'center';
                element.style.fontSize = '1.5rem';
            });
        }
    }, [outputs]);
    

    const renderChordPro = (chordProContent, originalKey, targetKey) => {
        try {
            if (chordProContent) {
                console.log(originalKey, targetKey);
                const parser = new ChordSheetJS.ChordProParser();
                const distance = Key.distance(originalKey, targetKey);
                chordProContent = chordProContent.replaceAll('{ci:', '{c:');
                const song = parser.parse(chordProContent);
                const transposedSong = song.transpose(distance);
                const formatter = new ChordSheetJS.HtmlTableFormatter();
                return formatter.format(transposedSong);
            }
            return '';
        } catch (error) {
            console.error(error);
            return '';
        }
    };

    const renderPrintOutput = (chordProContent, originalKey, targetKey) => {
        try {
            if (chordProContent) {
                console.log(originalKey, targetKey);
                const parser = new ChordSheetJS.ChordProParser();
                const distance = Key.distance(originalKey, targetKey);
                chordProContent = chordProContent.replaceAll('{ci:', '{c:');
                const song = parser.parse(chordProContent);
                const transposedSong = song.transpose(distance);
                const formatter = new ChordSheetJS.TextFormatter();
                return formatter.format(transposedSong);
            }
            return '';
        } catch (error) {
            console.error(error);
            return '';
        }
    };
  
    return (
        <div className="bg-gray-100">
            <div className="print-output">
                {outputs.map((output) => <pre key={output.id} dangerouslySetInnerHTML={{ __html: renderPrintOutput(output.chordsheets.content, output.chordsheets.key, output.targetKey) }} />)}
            </div>
            {setlist && <h2 className="text-center text-2xl font-bold sticky top-0 left-0 z-10 w-full bg-gray-700 text-white py-4 shadow-md">{setlist.name}</h2>}
            <div className="view-setlist flex flex-col items-center">
                {outputs.map((output) => <div key={output.id} dangerouslySetInnerHTML={{ __html: renderChordPro(output.chordsheets.content, output.chordsheets.key, output.targetKey) }} className="sheet mt-4 bg-white shadow-lg rounded-lg p-6 max-w-3xl w-full border border-gray-200" />)}
            </div>
            <footer className="text-center text-sm text-gray-500 pt-4">
                <p>Generated by <a href={window.location.origin} target="_blank" rel="noopener noreferrer"><Guitar className="inline-block" /> Team Chords</a></p>
            </footer>
        </div>
    );
};

export default SetListView;

